/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pbl3quanlynhanvien.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import pbl3quanlynhanvien.BLL.QuanLyDiemDanhBLL;
import pbl3quanlynhanvien.DAL.LichDAO;
import pbl3quanlynhanvien.DAL.MessageDialogHelper;
import pbl3quanlynhanvien.DAL.NhanVien_LichDAO;
import pbl3quanlynhanvien.DTO.Nhanvien_Lich;
import pbl3quanlynhanvien.DTO.ShareData;

/**
 *
 * @author PC
 */
public class DiemDanhPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiemDanhPanel
     */
    public DiemDanhPanel() {
        initComponents();
        initLable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblCurrentDay = new javax.swing.JLabel();
        lblDiemDanh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTimeDiemDanh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSoNgayDiLam = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnDiemDanh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTimeStart = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTimeEnd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBuoiLam = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("ĐIỂM DANH NHÂN VIÊN");

        jLabel2.setText("Ngày hiện tại:");

        lblCurrentDay.setText("2022-05-23");

        lblDiemDanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDiemDanh.setForeground(new java.awt.Color(255, 102, 51));
        lblDiemDanh.setText("CHƯA ĐIỂM DANH");

        jLabel5.setText("Điểm danh lúc:");

        jLabel7.setText("Số ngày đi làm:");

        btnDiemDanh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDiemDanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/diemdanh.png"))); // NOI18N
        btnDiemDanh.setText("ĐIỂM DANH");
        btnDiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemDanhActionPerformed(evt);
            }
        });

        jLabel3.setText("Điểm danh lần 1 lúc:");

        lblTimeStart.setText("null");

        jLabel6.setText("Điểm danh lần 2 lúc:");

        lblTimeEnd.setText("null");

        jLabel4.setText("Buổi làm: ");

        lblBuoiLam.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSoNgayDiLam)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCurrentDay)
                                                .addGap(124, 124, 124)
                                                .addComponent(lblDiemDanh))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTimeDiemDanh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblBuoiLam)
                                                .addGap(281, 281, 281)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(btnDiemDanh))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(265, 265, 265)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTimeStart)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTimeEnd)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCurrentDay)
                    .addComponent(lblDiemDanh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeDiemDanh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblBuoiLam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoNgayDiLam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(lblTimeStart)
                    .addComponent(jLabel6)
                    .addComponent(lblTimeEnd))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDiemDanh)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initLable(){
        
                    
        ShareData data = new ShareData();
        Nhanvien_Lich nhanvien = null;
        try {
                    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
                    LocalDateTime now = LocalDateTime.now();  
                    String day = dtf.format(now);
                    
                        DateFormat dateFormat1 = new SimpleDateFormat("HH:mm:ss");

                        Date date1 = new Date();
                        Date timeNow = dateFormat1.parse(dateFormat1.format(date1));
                         String buoi = LichDAO.getInstance().checkBuoiLam(timeNow);
                         
                         lblCurrentDay.setText(day);
                    
                        lblBuoiLam.setText(buoi);
                        int id_lich = LichDAO.getInstance().getID_lichByNgayVaBuoi(buoi);
                        nhanvien = NhanVien_LichDAO.getInstance().getNhanVienLichByIdLichAndIdNhanvien(id_lich, data.getId_nhanvien());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        if(nhanvien != null)
                {
                    if(nhanvien.getThoigianbatdau() != null && nhanvien.getThoigianketthuc() != null)
            {
                    lblDiemDanh.setText("ĐÃ ĐIỂM DANH");
            }
        
        if(nhanvien.getThoigianbatdau() != null) {
            lblTimeStart.setText(nhanvien.getThoigianbatdau().toString());
        }        else {
            lblTimeStart.setText("Chưa điểm danh");
        }
        if(nhanvien.getThoigianketthuc()!= null) {
            lblTimeEnd.setText(nhanvien.getThoigianketthuc().toString());
        }else {
            lblTimeEnd.setText("Chưa điểm danh");
        }
                }
        
        
    }
    
    private void btnDiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemDanhActionPerformed
        // TODO add your handling code here:
        
        ShareData data = new ShareData();
        
        boolean isSuccess = QuanLyDiemDanhBLL.getInstance().thucHienDiemDanh(data.getId_nhanvien());
        if(isSuccess)
        {
            try {
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                    Date date = new Date();
                    Date now = dateFormat.parse(dateFormat.format(date));
                    java.sql.Timestamp sqlTS = new java.sql.Timestamp(now.getTime());
                    lblTimeDiemDanh.setText(sqlTS.toString());
                    lblDiemDanh.setText("ĐÃ ĐIỂM DANH");
                    MessageDialogHelper.showMessageDialog(this, "Điểm Danh Thành Công", "Thông Báo");
            } catch (Exception e) {
            }
        }else {
            MessageDialogHelper.showErrorDialog(this, "Không phải ca điểm danh của bạn hoặc bạn đã thực hiện điểm danh đủ số lần quy định", "ERROR");
        }
        
        initLable();
    }//GEN-LAST:event_btnDiemDanhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiemDanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBuoiLam;
    private javax.swing.JLabel lblCurrentDay;
    private javax.swing.JLabel lblDiemDanh;
    private javax.swing.JLabel lblSoNgayDiLam;
    private javax.swing.JLabel lblTimeDiemDanh;
    private javax.swing.JLabel lblTimeEnd;
    private javax.swing.JLabel lblTimeStart;
    // End of variables declaration//GEN-END:variables
}
