
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbl3quanlynhanvien.view;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import pbl3quanlynhanvien.DAL.UserDAO;
import pbl3quanlynhanvien.DTO.ShareData;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     * 
     */
    
    private QLNVForm QLNVPanel;
    private LichLamViecNhanVienPanel LichLamViecAllNVPanel;
    private DangKyLichBanPanel dangKyLichBanPanel;
    private TInhLuongPanel TinhLuongPanel;
    private LichLamViecMoiNhanVienPanel LichLamViec1NVPanel;
    private DiemDanhPanel diemDanhPanel;
    private DoiMatKhauPanel doiMatKhauPanel;
    private DetailProfile detailProfilePanel;
    
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnLogOut = new javax.swing.JButton();
        btnQLNV = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnLichLamViec = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnTinhLuong = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnDangKyLichBan = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        btnDiemDanh = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        btnLichLamViecMoiNhanVien = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        btnAboutUs = new javax.swing.JButton();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        jSeparator13 = new javax.swing.JSeparator();
        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        lblLoginRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuHeThong_Logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuHeThong_DoiMK = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        mnuHeThong_Exit = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        mnuDanhMuc = new javax.swing.JMenu();
        mnuDanhMuc_QLNV = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuDanhMuc_LichLamViec = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuDanhMuc_TinhLuong = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuDanhMuc_DiemDanh = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuDanhMuc_LichLamViec1NV = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        mnuDanhSach_ThongTinCaNhan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDangKyBan = new javax.swing.JMenu();
        mnuDangKyBan_DangKyBan = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUs = new javax.swing.JMenu();
        mnuAboutUs_AboutUs = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator11);
        jToolBar1.add(jSeparator7);

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/logout-48.png"))); // NOI18N
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setFocusable(false);
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogOut);

        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/qlnv48.png"))); // NOI18N
        btnQLNV.setText("Quản lý nhân viên");
        btnQLNV.setFocusable(false);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLNV);
        jToolBar1.add(jSeparator8);

        btnLichLamViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/calendal-48.png"))); // NOI18N
        btnLichLamViec.setText(" Xếp Lịch làm việc");
        btnLichLamViec.setFocusable(false);
        btnLichLamViec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichLamViec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLichLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichLamViecActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLichLamViec);
        jToolBar1.add(jSeparator9);

        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/payroll-48.png"))); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.setFocusable(false);
        btnTinhLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTinhLuong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTinhLuong);
        jToolBar1.add(jSeparator10);
        jToolBar1.add(jSeparator12);

        btnDangKyLichBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/dklichban-48.png"))); // NOI18N
        btnDangKyLichBan.setText("Đăng Ký Lịch Bận");
        btnDangKyLichBan.setFocusable(false);
        btnDangKyLichBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangKyLichBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangKyLichBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyLichBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangKyLichBan);
        jToolBar1.add(jSeparator15);

        btnDiemDanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/diemdanh-48.png"))); // NOI18N
        btnDiemDanh.setText("Điểm Danh");
        btnDiemDanh.setFocusable(false);
        btnDiemDanh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiemDanh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemDanhActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDiemDanh);
        jToolBar1.add(jSeparator18);

        btnLichLamViecMoiNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/lichlamviec1nv-48.png"))); // NOI18N
        btnLichLamViecMoiNhanVien.setText("Lịch Làm Việc Nhân Viên");
        btnLichLamViecMoiNhanVien.setFocusable(false);
        btnLichLamViecMoiNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichLamViecMoiNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLichLamViecMoiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichLamViecMoiNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLichLamViecMoiNhanVien);
        jToolBar1.add(jSeparator20);
        jToolBar1.add(jSeparator19);

        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/gioithieu-48.png"))); // NOI18N
        btnAboutUs.setText("Giới Thiệu");
        btnAboutUs.setFocusable(false);
        btnAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAboutUs);
        jToolBar1.add(jSeparator21);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLoginName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginName.setText("Username");

        lblLoginRole.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblLoginRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginRole.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblLoginRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginName)
                .addGap(18, 18, 18)
                .addComponent(lblLoginRole, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        mnuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/hethong-16.png"))); // NOI18N
        mnuHeThong.setText("Hệ thống");

        mnuHeThong_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/logout-icon-16.png"))); // NOI18N
        mnuHeThong_Logout.setText("Đăng xuất");
        mnuHeThong_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThong_LogoutActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuHeThong_Logout);
        mnuHeThong.add(jSeparator1);

        mnuHeThong_DoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/change-password-16.png"))); // NOI18N
        mnuHeThong_DoiMK.setText("Đổi mật khẩu");
        mnuHeThong_DoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThong_DoiMKActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuHeThong_DoiMK);
        mnuHeThong.add(jSeparator22);

        mnuHeThong_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        mnuHeThong_Exit.setText("Thoát");
        mnuHeThong_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThong_ExitActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuHeThong_Exit);
        mnuHeThong.add(jSeparator14);

        jMenuBar1.add(mnuHeThong);

        mnuDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/danhmuc-16.png"))); // NOI18N
        mnuDanhMuc.setText("Danh mục");

        mnuDanhMuc_QLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/qlnv-16.png"))); // NOI18N
        mnuDanhMuc_QLNV.setText("Quản lý nhân viên");
        mnuDanhMuc_QLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhMuc_QLNVActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhMuc_QLNV);
        mnuDanhMuc.add(jSeparator3);

        mnuDanhMuc_LichLamViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/calendal-16.png"))); // NOI18N
        mnuDanhMuc_LichLamViec.setText("Lịch làm việc\t");
        mnuDanhMuc_LichLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhMuc_LichLamViecActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhMuc_LichLamViec);
        mnuDanhMuc.add(jSeparator4);

        mnuDanhMuc_TinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/payroll-16.png"))); // NOI18N
        mnuDanhMuc_TinhLuong.setText("Tính lương ");
        mnuDanhMuc_TinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhMuc_TinhLuongActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhMuc_TinhLuong);
        mnuDanhMuc.add(jSeparator5);

        mnuDanhMuc_DiemDanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/diemdanh-16.png"))); // NOI18N
        mnuDanhMuc_DiemDanh.setText("Điểm danh");
        mnuDanhMuc_DiemDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhMuc_DiemDanhActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhMuc_DiemDanh);
        mnuDanhMuc.add(jSeparator6);

        mnuDanhMuc_LichLamViec1NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/lichlamvie1nv-16.png"))); // NOI18N
        mnuDanhMuc_LichLamViec1NV.setText("Lịch của mỗi nhân viên");
        mnuDanhMuc_LichLamViec1NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhMuc_LichLamViec1NVActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhMuc_LichLamViec1NV);
        mnuDanhMuc.add(jSeparator23);

        mnuDanhSach_ThongTinCaNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/profile-16.png"))); // NOI18N
        mnuDanhSach_ThongTinCaNhan.setText("Thông tin cá nhân");
        mnuDanhSach_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDanhSach_ThongTinCaNhanActionPerformed(evt);
            }
        });
        mnuDanhMuc.add(mnuDanhSach_ThongTinCaNhan);
        mnuDanhMuc.add(jSeparator2);

        jMenuBar1.add(mnuDanhMuc);

        mnuDangKyBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/lichban-16.png"))); // NOI18N
        mnuDangKyBan.setText("Đăng ký lịch bận");

        mnuDangKyBan_DangKyBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/image 49.png"))); // NOI18N
        mnuDangKyBan_DangKyBan.setText("Đăng ký lịch bận ");
        mnuDangKyBan_DangKyBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangKyBan_DangKyBanActionPerformed(evt);
            }
        });
        mnuDangKyBan.add(mnuDangKyBan_DangKyBan);
        mnuDangKyBan.add(jSeparator16);

        jMenuBar1.add(mnuDangKyBan);

        mnuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/Actions-help-about-icon-16.png"))); // NOI18N
        mnuAboutUs.setText("Giới thiệu");

        mnuAboutUs_AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbl3quanlynhanvien/icons/Actions-help-about-icon-16.png"))); // NOI18N
        mnuAboutUs_AboutUs.setText("Giới thiệu");
        mnuAboutUs_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUs_AboutUsActionPerformed(evt);
            }
        });
        mnuAboutUs.add(mnuAboutUs_AboutUs);
        mnuAboutUs.add(jSeparator17);

        jMenuBar1.add(mnuAboutUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tplMainBoard)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                        .addGap(387, 387, 387)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHeThong_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThong_LogoutActionPerformed
        // TODO add your handling code here:
        btnLogOutActionPerformed(evt);
    }//GEN-LAST:event_mnuHeThong_LogoutActionPerformed

    private void mnuDanhMuc_TinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhMuc_TinhLuongActionPerformed
        // TODO add your handling code here:
        btnTinhLuongActionPerformed(evt);
    }//GEN-LAST:event_mnuDanhMuc_TinhLuongActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        // TODO add your handling code here:
        if(QLNVPanel == null)
        {
            QLNVPanel = new QLNVForm();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/qlnv-16.png"));
            
            tplMainBoard.addTab("Quản lý nhân viên", icon, QLNVPanel, "Quản lý nhân viên");
        }
        
        tplMainBoard.setSelectedComponent(QLNVPanel);
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void mnuDanhMuc_QLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhMuc_QLNVActionPerformed
        // TODO add your handling code here:
        btnQLNVActionPerformed(evt);
    }//GEN-LAST:event_mnuDanhMuc_QLNVActionPerformed

    private void btnLichLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichLamViecActionPerformed
        // TODO add your handling code here:
         if(LichLamViecAllNVPanel == null)
        {
            LichLamViecAllNVPanel = new LichLamViecNhanVienPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/lichlamviec-16.png"));
            
            tplMainBoard.addTab("Lịch làm việc tất cả nhân viên", icon, LichLamViecAllNVPanel, "Lịch làm việc tất cả nhân viên");
        }
        
        tplMainBoard.setSelectedComponent(LichLamViecAllNVPanel);
    }//GEN-LAST:event_btnLichLamViecActionPerformed

    private void mnuDanhMuc_LichLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhMuc_LichLamViecActionPerformed
        // TODO add your handling code here:
        btnLichLamViecActionPerformed(evt);
    }//GEN-LAST:event_mnuDanhMuc_LichLamViecActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        if(TinhLuongPanel == null)
        {
            TinhLuongPanel = new TInhLuongPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/payroll-16.png"));
            
            tplMainBoard.addTab(" Tính lương", icon, TinhLuongPanel, " Tính lương");
        }
        
        tplMainBoard.setSelectedComponent(TinhLuongPanel);
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void mnuDanhMuc_DiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhMuc_DiemDanhActionPerformed
        // TODO add your handling code here:
        btnDiemDanhActionPerformed(evt);
    }//GEN-LAST:event_mnuDanhMuc_DiemDanhActionPerformed

    private void mnuHeThong_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThong_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuHeThong_ExitActionPerformed

    private void mnuDangKyBan_DangKyBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangKyBan_DangKyBanActionPerformed
        // TODO add your handling code here:
        if(dangKyLichBanPanel == null)
        {
            dangKyLichBanPanel = new DangKyLichBanPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/image 49.png"));
            
            tplMainBoard.addTab("Đăng kí lịch bận", icon, dangKyLichBanPanel, "Đăng kí lịch bận");
        }
        
        tplMainBoard.setSelectedComponent(dangKyLichBanPanel);
    }//GEN-LAST:event_mnuDangKyBan_DangKyBanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LoginForm login = new LoginForm(this, true);
        login.setVisible(true);
        processLoginSuccessful();
    }//GEN-LAST:event_formWindowOpened

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        tplMainBoard.removeAll();
        QLNVPanel = null;
        LichLamViecAllNVPanel = null;
        dangKyLichBanPanel = null;
        TinhLuongPanel = null;
        LichLamViec1NVPanel = null;
        diemDanhPanel = null;
        doiMatKhauPanel = null;
        LoginForm login = new LoginForm(this, true);
        login.setVisible(true);
        processLoginSuccessful();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDangKyLichBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyLichBanActionPerformed
        // TODO add your handling code here:
        mnuDangKyBan_DangKyBanActionPerformed(evt);
    }//GEN-LAST:event_btnDangKyLichBanActionPerformed

    private void btnDiemDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemDanhActionPerformed
        // TODO add your handling code here:
         if(diemDanhPanel == null)
        {
            diemDanhPanel = new DiemDanhPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/diemdanh-16.png"));
            
            tplMainBoard.addTab("Điểm danh", icon, diemDanhPanel, "Điểm danh");
        }
        
        tplMainBoard.setSelectedComponent(diemDanhPanel);
    }//GEN-LAST:event_btnDiemDanhActionPerformed

    private void mnuDanhMuc_LichLamViec1NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhMuc_LichLamViec1NVActionPerformed
        // TODO add your handling code here:
        if(LichLamViec1NVPanel == null)
        {
            LichLamViec1NVPanel = new LichLamViecMoiNhanVienPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/lichlamvie1nv-16.png"));
            
            tplMainBoard.addTab("Lịch Làm Việc Của Nhân Viên: " + UserDAO.getInstance().getNameByID_Nhanvien(), icon, LichLamViec1NVPanel, "Lịch Làm Việc");
        }
        
        tplMainBoard.setSelectedComponent(LichLamViec1NVPanel);
    }//GEN-LAST:event_mnuDanhMuc_LichLamViec1NVActionPerformed

    private void btnLichLamViecMoiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichLamViecMoiNhanVienActionPerformed
        // TODO add your handling code here:
        mnuDanhMuc_LichLamViec1NVActionPerformed(evt);
    }//GEN-LAST:event_btnLichLamViecMoiNhanVienActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        AboutUs aboutUs = new AboutUs(this, true);
        
        aboutUs.setVisible(true);
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void mnuAboutUs_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUs_AboutUsActionPerformed
        // TODO add your handling code here:
        btnAboutUsActionPerformed(evt);
    }//GEN-LAST:event_mnuAboutUs_AboutUsActionPerformed

    private void mnuHeThong_DoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThong_DoiMKActionPerformed
        // TODO add your handling code here:
        if(doiMatKhauPanel == null)
        {
            doiMatKhauPanel = new DoiMatKhauPanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/lichlamvie1nv-16.png"));
            
            tplMainBoard.addTab("Đổi mật khẩu", icon, doiMatKhauPanel, "Đổi mật khẩu");
        }
        
        tplMainBoard.setSelectedComponent(doiMatKhauPanel);
    }//GEN-LAST:event_mnuHeThong_DoiMKActionPerformed

    private void mnuDanhSach_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDanhSach_ThongTinCaNhanActionPerformed
        // TODO add your handling code here:
        if(detailProfilePanel == null)
        {
            detailProfilePanel = new DetailProfile();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/pbl3quanlynhanvien/icons/lichlamvie1nv-16.png"));
            
            tplMainBoard.addTab("", icon, detailProfilePanel, "Đổi mật khẩu");
        }
        
        tplMainBoard.setSelectedComponent(detailProfilePanel);
    }//GEN-LAST:event_mnuDanhSach_ThongTinCaNhanActionPerformed

    private void processLoginSuccessful(){
        tplMainBoard.removeAll();
        lblLoginName.setText(ShareData.getNguoiDangNhap().getUsername());
        lblLoginRole.setText(ShareData.getNguoiDangNhap().getRole());
        
        if(ShareData.getNguoiDangNhap().getRole().equals("Admin"))
            {
                mnuDangKyBan_DangKyBan.setEnabled(false);
                mnuDanhMuc_DiemDanh.setEnabled(false);
                mnuDanhMuc_LichLamViec1NV.setEnabled(false);
                btnDiemDanh.setEnabled(false);
                btnDangKyLichBan.setEnabled(false);
                btnLichLamViecMoiNhanVien.setEnabled(false);
                mnuDanhSach_ThongTinCaNhan.setEnabled(false);
                mnuDanhMuc_QLNV.setEnabled(true);
                mnuDanhMuc_LichLamViec.setEnabled(true);
                mnuDanhMuc_TinhLuong.setEnabled(true);
                btnQLNV.setEnabled(true);
                btnLichLamViec.setEnabled(true);
                btnTinhLuong.setEnabled(true);
            } else if(ShareData.getNguoiDangNhap().getRole().equals("User"))
            {
                mnuDangKyBan_DangKyBan.setEnabled(true);
                mnuDanhMuc_DiemDanh.setEnabled(true);
                mnuDanhMuc_LichLamViec1NV.setEnabled(true);
                btnDiemDanh.setEnabled(true);
                btnDangKyLichBan.setEnabled(true);
                btnLichLamViecMoiNhanVien.setEnabled(true);
                mnuDanhSach_ThongTinCaNhan.setEnabled(true);
                
                mnuDanhMuc_QLNV.setEnabled(false);
                mnuDanhMuc_LichLamViec.setEnabled(false);
                mnuDanhMuc_TinhLuong.setEnabled(false);
                btnQLNV.setEnabled(false);
                btnLichLamViec.setEnabled(true);
                btnTinhLuong.setEnabled(false);
            } else return;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnDangKyLichBan;
    private javax.swing.JButton btnDiemDanh;
    private javax.swing.JButton btnLichLamViec;
    private javax.swing.JButton btnLichLamViecMoiNhanVien;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblLoginRole;
    private javax.swing.JMenu mnuAboutUs;
    private javax.swing.JMenuItem mnuAboutUs_AboutUs;
    private javax.swing.JMenu mnuDangKyBan;
    private javax.swing.JMenuItem mnuDangKyBan_DangKyBan;
    private javax.swing.JMenu mnuDanhMuc;
    private javax.swing.JMenuItem mnuDanhMuc_DiemDanh;
    private javax.swing.JMenuItem mnuDanhMuc_LichLamViec;
    private javax.swing.JMenuItem mnuDanhMuc_LichLamViec1NV;
    private javax.swing.JMenuItem mnuDanhMuc_QLNV;
    private javax.swing.JMenuItem mnuDanhMuc_TinhLuong;
    private javax.swing.JMenuItem mnuDanhSach_ThongTinCaNhan;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuHeThong_DoiMK;
    private javax.swing.JMenuItem mnuHeThong_Exit;
    private javax.swing.JMenuItem mnuHeThong_Logout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
